apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jio20-session
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/enable-websocket: "true"
spec:
  rules:
    - host: session.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jio20-session
                port:
                  number: 80


